name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate repo structure
        run: |
          test -d infra && echo "infra ok"
          test -d services && echo "services ok"
          test -d sim && echo "sim ok"
          test -d policies && echo "policies ok"
          test -d audit && echo "audit ok"
          test -d ui && echo "ui ok"
          test -d ops && echo "ops ok"
